services:
  - type: web
    name: mi-finanzas
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: /*.css
        name: Content-Type
        value: text/css; charset=utf-8